version: 2.1

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:10.13.0 # the primary container, where your job's commands are run
    working_directory: /tmp/workspace
    steps:
      - checkout # check out the code in the project directory
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm install
          working_directory: /tmp/workspace/cli
      - run:
          command: npm run build
          working_directory: /tmp/workspace/cli
      - run:
          command: npm run test
          working_directory: /tmp/workspace/cli